### ISSUE TITLE
[BUG] Aqara Motion sensor always reports the temperature 29C 

### ISSUE THREAD

**Issue by sergey-suloev** [zigpy/zha-device-handlers#1358]
The snapshot is taken when the sensor is placed outdoor where the temperature at the moment is +5C

![Screenshot from 2022-02-15 16-31-58](https://user-images.githubusercontent.com/6279627/154072405-afb3a5cd-077c-4062-902e-e44adaeacb80.png)

**Comment by sergey-suloev** [comment]
[home-assistant.log](https://github.com/zigpy/zha-device-handlers/files/8069550/home-assistant.log)

**Comment by dontinelli** [comment]
I have an issue with the Aqara Single Switch T1, which could be related to the above:
Since the device temperature is reported, it seems to be constantly at 0.2°C, while I would expect a temperature of approx. 15°C. Interestingly, when I get the device temperature over the "cluster" dialog, it reports a device temperature of (currently) 15°C.
Another switch (also located in the cellar, but in a different room) reports a temperature of 0.1°C or 0.2°C in the entity but 16°C in the "cluster" dialog (which could be correct). A third switch constantly reports 0.2°C in the entity but 25°C in the "cluster" dialog (which seems to be approx. 5° too high, but this could also be an inaccuracy of the measurement, I guess).
