### ISSUE TITLE
[BUG] LLKZMK11LM: power metering disappears after restart

### ISSUE THREAD

**Issue by mikoff** [zigpy/zha-device-handlers#1382]
**Describe the bug**
On Home Assistant restart, the power monitoring entity of the device disappears. If we go to the cluster management screen we see that the device can read proper wattage, but the entities report “Unavailable” status.
The option to "Reconfigure" does not help.

**To Reproduce**
1. Pair LLKZMK11LM
2. Check that power monitoring works and reports
3. Reboot HA
4. Power monitoring utilities are missing

**Screenshots**
![1](https://user-images.githubusercontent.com/3890953/154862857-99c6f874-5416-4d1e-a100-0311302f1f8f.png)
![2](https://user-images.githubusercontent.com/3890953/154862870-ffb58f77-ad3f-4fb2-a01d-8c11d00b0a23.png)

**Additional context**
The problem was discussed by other users on HA forum, for example:
https://community.home-assistant.io/t/aqara-lumi-2-channel-relay-with-zha/356984

**Comment by mazerte** [comment]
It may be related to this one to https://github.com/zigpy/zha-device-handlers/issues/1337.

On my side I get the same problem with the Aqara Smart Plug. Clusters are reporting good metrics but entities are unavailable.

**Comment by dmulcahey** [comment]
Do you have the same errors in the logs that the linked issue above does?

**Comment by leonardpitzu** [comment]
Logs are empty. Same the entities.

**Comment by jims-code** [comment]
The strange behaviour mentioned in this issue is shown by devices that were connected some days ago. Devices that were connected last year work fine.

Maybe there are some hints in these issues that help finding the reason for this strange behaviour:
https://github.com/home-assistant/core/issues/67644
https://github.com/zigpy/zha-device-handlers/issues/1337

The file plug_mmeu01.py has been updated 3 months ago. It might be that this caused an unwanted side effect.
https://github.com/zigpy/zha-device-handlers/pull/1252

**Comment by kvvoff** [comment]
Is there any progress in solving the problem? I have the same with LLKZMK11LM

**Comment by jims-code** [comment]
For the Aqara Smart Plug the problem has been solved in zigpy/zha-device-handlers Release 0.0.73. The installation was done automatically by a Home Assistant update.

More details concerning the bug can be found here: https://github.com/home-assistant/core/issues/67644

**Comment by kvvoff** [comment]
for LLKZMK11LM still doesn't work. Latest version of HA
