### ISSUE TITLE
[BUG] Philips SML001 sensitivity setting not working properly

### ISSUE THREAD

**Issue by cramer52** [zigpy/zha-device-handlers#1576]
**Describe the bug**
I am using the quirk motion.py and the device class is reported as phillips.motion.PhilipsMotion. I'm trying to adjust the sensitivity of my Philips Hue SML001 by changing the Sensitivity (id: 0x0030) value in the OccupancyCluster to 0. However, it does not accept the change reports the changed value afterwards with "None" and when restarting the HA the default value 2 is displayed again.

**To Reproduce**
1. Go to Device Settings -> Cluster -> OccupancyCluster -> sensitivity -> 0
2. Click on set zigbee attribute
3. Click on get zigbee attribute

**Expected behavior**
The corresponding value is set and saved for the sensitivity.

**Comment by TheJulianJES** [comment]
I cannot reproduce the issue on a Philips Hue first gen outdoor sensor (SML002) that's basically identical to a SML001.
I was able to set the sensitivity to 0 and read back the attribute without any issues.

![image](https://user-images.githubusercontent.com/6409465/170327701-a164d834-f2c4-4b01-ac85-fdcb38095fca.png)


Since you did not fill out the issue template, please post the "Diagnostic information" (which can be acquired by clicking on the "Download Diagnostics" button in the device settings view). (It'll also include things like your Home Assistant version and more).
