### ISSUE TITLE
Moes Model ZSS-ZK-THL - TS0222 _TYZB01_kvwjujy9

### ISSUE THREAD

**Issue by evlo** [zigpy/zha-device-handlers#1747]
I was wondering if anyone managed to device above mentioned reliably?

https://zigbee.blakadder.com/Moes_ZSS-ZK-THL.html - there is some kind of workaround template mentioned, but I think i won't every really work as the device is just showing zeroes and resetting(?) constantly
https://www.zigbee2mqtt.io/devices/ZSS-ZK-THL.html
https://github.com/zigpy/zha-device-handlers/issues/961

In my experience it works a bit better with zigbee2mqtt, also with tuya hub it still sometimes read zeros.

Since there is E1 reported as temperature on display or the battery icon, or exclamation mark on the display, and display flashing "black/white" even with fresh battery etc. I wonder if it might be super sensitive to batteries ore something.

Also do you think that in the compatibility databases devices like this should really be considered unsupported since the behaviour is so bad?

....................................

I did some experiments and with 3.3V battery it seems kinda oka, but anything under 3V it is just useless, so would require hardware modding to work and even after that only with tuya zigbee gateway doing some magical tricks with it

**Comment by almico** [comment]
I keep giving this device a chance every few months. Both with Tuya gateway, and with ZHA.
Every time, like this time, I have to take the battery out and put the device back in its box. Hoping for some future miracle 😭

**Comment by evlo** [comment]
It is still mindboggling that devices like this get into production.

**Comment by igorsantos07** [comment]
I was never able to get it to work properly with the HA Zigbee mesh, but since this is pretty much my only way to get lux without messing with ESPHome, I decided to throw more money onto AliExpress and tried to buy a Tuya gateway. Pairing them together with my Tuya account does the trick - and yep, I now have a second Zigbee network running on my office, _just for this freaking sensor_ 🙄 and data do go through Tuya cloud 🫠 but at least it's pretty much instant.

Ddetails were discussed confusingly to exhaustion at https://github.com/zigpy/zha-device-handlers/issues/961

**Comment by evlo** [comment]
And battery life is ok on tuya gw for you?

**Comment by igorsantos07** [comment]
Can't say for sure... I popped in a used battery and I just started using
it 2 days ago, so...

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by igorsantos07** [comment]
If anyone end up here still looking for what to do - I've been using this through the Tuya gateway sort of successfully since my last comments. I think I've already used two batteries (maybe three?) and it bugs out constantly throughout the month - sometimes it stops showing any value, sometimes just temp/humid, sometimes it crashes... Those are all solved by, you guessed, removing and re-adding the battery, what caused me to break one of the tiny legs of its battery panel already.

**Comment by evlo** [comment]
I do only use LYWSD03MMC and CGG1 now. I'm sharing this as those are in my test best devices of this kind. Also not zigbee, but since switching to BT in general I do not remember having any issue other then HW failure of the device that was outside.
