### ISSUE TITLE
[BUG] Tuya Soil Sensor (_TZE200_myd45weu) wrong battery configuration

### ISSUE THREAD

**Issue by mkoppanen** [zigpy/zha-device-handlers#2384]
### Bug description

I noticed that my soil temp/humidity sensor keeps showing incorrect battery level values. I noticed that in the diagnostics that it's using TuyaPowerConfigurationCluster2AAA, while actually the device takes 2 AA batteries. 

The device identifier is TS0601 by _TZE200_myd45weu

### Steps to reproduce

Add the device and look into the "Clusters"

### Expected behavior

The device is identified with 2 AA batteries.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by Copyrighter** [comment]
I have the same issue.
The battery level is always at 20%, the device _TZE200_myd45weu, TuyaPowerConfigurationCluster2AAA instead of 2 AA batteries.

Anyone can assist?
@mbo18 Maybe You can assist? I saw Your commit "Add Tuya soil sensor _TZE200_ga1maeof variant (#2498)"
@TheJulianJES 

Tuya Zigbee Plant Soil Sensor GXM-01
