### ISSUE TITLE
Question: Lights - Enable Smooth transition?

### ISSUE THREAD

**Issue by RefineryX** [zigpy/zha-device-handlers#240]
Currently using some Hue bulbs with ZHA. Everything is working brilliantly.

When I manually change the brightness or colour of the bulbs, it instantly flips to the new setting without a period of transition. On Deconz and also the Hue bridge directly, when changing the brightness/colour it transitions from the current to the new setting smoothly.

Does anyone know if this is possible with ZHA?

I know you can do this on scenes etc but we do a lot of manual changes in our house.

**Comment by Adminiuga** [comment]
well, in lovelace UI is there a field for "transition" during brighness/color changes?
If you want it for manual contol, you would need to modify card for the light control to include transition attribute. Otherwise it is already available for service calls.

**Comment by SimplyGardner** [comment]
Thanks @Adminiuga. I am mainly controlling my lights from the HomeKit platform. HA exposes these lights to HomeKit for me.

**Comment by SimplyGardner** [comment]
My lights support the fading. As a test I added another Hue bulb and called the ``light.turn_on`` service - incorporating the ``transition`` item.

How do I get the default behaviour of ZHA to always use a transition when changing the brightness or colour of lights? It uses a transition when turning them on and off - fading it and out smoothly.

<img width="492" alt="Screenshot 2020-01-14 at 18 19 51" src="https://user-images.githubusercontent.com/46373533/72385708-fb699e80-3717-11ea-8ed0-6a5e07e262f9.png">

**Comment by dmulcahey** [comment]
Are you asking about when controlling from automations? or even when toggling in the UI? If it is the later we would need to change the light class to support this.

**Comment by SimplyGardner** [comment]
Hi @dmulcahey - when controlling via the UI.

I have these lights also exposed to HomeKit via Home Assistant and changing the class would probably help to enable to smooth transition here also.

**Comment by Adminiuga** [comment]
IMO this is a setting which can't make all users happy.  I think if not specified by the calling service, the light should turn on as fast as possible.

**Comment by dmulcahey** [comment]
I agree @Adminiuga but I wanna investigate something. I think this setting can be stored on the bulbs. If so, we can default it to 0 / no transition and allow people to change it. If that’s the case we can change the light class to read this from the lights and use it as a default if it isn’t sent in the call. Does that make sense?

**Comment by dmulcahey** [comment]
hrm, looks like the attrs are optional and the singled bulbs I have don't support them.

**Comment by Adminiuga** [comment]
Can transition time be specified in lights profile?

**Comment by Adminiuga** [comment]
Apparently not

**Comment by tube0013** [comment]
FWIW The Osram bulbs I used to use would default to a 5 second transition. I could change it via the level control cluster and did it via an automation when the light came back from unavailable. No bulb since (innr, hue, echo smart or Ledvance) have supported modifying the transition time via cluster

**Comment by SimplyGardner** [comment]
> @Adminiuga  IMO this is a setting which can't make all users happy.

Agreed - although integrating a smooth transition with ensure that ZHA is consistent with other platforms such a Deconz and Hue. They all raise the lights smoothly. 

> @dmulcahey  hrm, looks like the attrs are optional and the singled bulbs I have don't support them.

I have a bunch of Hue bulbs I am happy to test with - you may need to show me how haha

> @tube0013 I could change it via the level control cluster 

Are you saying you can edit the light to interstate the transition for the bulb in question? If so how? Haha. I don’t mind going through all my bulbs and manually tweaking

**Comment by Adminiuga** [comment]
can https://github.com/home-assistant/home-assistant/pull/31452 help with this?

@SimplyGardner some lights support On/Off transition time attributes.
Go to Config -> Zha -> Pick your light -> Find Level Cluster. Write transition time in 1/10th of a second to:
- off transition time
- on transition time
- on/off transition time
![image](https://user-images.githubusercontent.com/5826160/73754097-d3c39000-4731-11ea-84b3-977060b0b438.png)

**Comment by SimplyGardner** [comment]
Hi @Adminiuga - thanks so much and apologies for the late reply. Only just getting round to testing this out but very excited to try.

I've added bulb to ZHA and the on transition and off transition is smooth. The issue is when changing the ``brightness`` or ``colour`` while the light is ``on``.

Looking at your screenshot... how do I add the items? I have attached a screenshot of what is in my system... What do I select in the ``Green`` box? 

Also what values do I add in the ``red`` and ``orange`` box?

<img width="623" alt="Screenshot 2020-02-26 at 21 08 26" src="https://user-images.githubusercontent.com/46373533/75388188-7360e200-58dc-11ea-82cc-f39e386969a0.png">

**Comment by miguelcaravantes** [comment]
the same issue i don't find the setting for change color smoothly as i did it with philips hue bridge

**Comment by TheJulianJES** [comment]
It seems like that Home Assistant Core had a DEFAULT_TRANSITION of 0.5 seconds in the past. (https://github.com/home-assistant/core/pull/26654/files)
In the upcoming 0.114 release, the default transition seems to be 1/10th of a second (in order to fix a bug): https://github.com/home-assistant/core/pull/38739

However, I'd also love to see a default transition of one second (or half a second again) in Home Assistant to match other lights with in-built transitions. I think there should be a setting for the default durations somewhere in Hass. I'm not sure if this is relevant to this project though.

**Comment by Adminiuga** [comment]
default transition was 0 --max speed for quite a few HA releases now, but apparently it is causing issue with some vendors so to improve the compatibility the default transition was changed to .1s. This is only applicable if you change the brightness or set duration, for plain on/off calls this doesn't do anything.

**Comment by TheJulianJES** [comment]
Yeah, okay. I'd love to be able to change the default transition time (when changing colors) from the .1s to 1s. (Every other light I use has a default transition time of 1s (Philips Hue for example (also when used via deCONZ, I think.)))
Not sure how easy something like this could be implemented though (regarding setting the value yourself).

**Comment by Adminiuga** [comment]
Do light profiles allow you to change the duration?

**Comment by dmulcahey** [comment]
I wanna say that was just worked on recently...

**Comment by TheJulianJES** [comment]
Yeah, this is already in the beta: https://rc.home-assistant.io/blog/2020/08/05/release-114/#other-noteworthy-changes
I'm not sure if this could be used to set a default transition for Hass though (?)

**Comment by TheJulianJES** [comment]
```
id,x,y,brightness,transition
group.all_lights.default,0,0,255,5
```
Tried this in the latest beta - the transition of 5 seconds works when turning the light on (and the colors fades when changing the color). However, this only happens if the color changes happens in the turn_on initial 5s transition.
So, I guess a "default color fade" is currently not possible with ZHA and Home Assistant.

**Comment by TheJulianJES** [comment]
Perhaps a "solution" to this "issue" could be to get the color profile and use that as a default transition duration (if present) here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/light.py#L195
(Not sure about this though.)

**Comment by TheJulianJES** [comment]
Today I tried my "custom implementation" of a one second transition between color/brightness changes on an up-to-date LEDVANCE Gardenpole light. It seems like this causes an "issue", when the brightness is changed, as the transition values of the brightness change are being displayed (for a short while) in the Home Assistant user interface.
So although this is not (and probably shouldn't be) a high priority for ZHA -- something like a transition setting on a per light basis might be a good idea for the future (this would also take some time and work to implement).

**Comment by TheJulianJES** [comment]
> Today I tried my "custom implementation" of a one second transition between color/brightness changes on an up-to-date LEDVANCE Gardenpole light. It seems like this causes an "issue", when the brightness is changed, as the transition values of the brightness change are being displayed (for a short while) in the Home Assistant user interface.
> So although this is not (and probably shouldn't be) a high priority for ZHA -- something like a transition setting on a per light basis might be a good idea for the future (this would also take some time and work to implement).

On newer ZHA hue bulbs which now send attribute reports (ZLL models of Hue lights don't), the brightness change of (even the 0.1s) transition is displayed in the UI - making it feel "laggy".
The bug report on the Hass repo is here:
https://github.com/home-assistant/core/issues/40300

**Comment by RefineryX** [comment]
Is there any update on this? My Phillips Hue bridge has broken and being forced to put all my lights through my Conbee II stick via ZHA.

I forgot about the issue with the changing of transitions via HomeKit. I would love to see the smooth transition with changing colours or brightness. 

On/off transition is absolutely fine.

**Comment by RefineryX** [comment]
Just playing around in HA. The service call works with adding ``transition: 1``. Is this something that I can integrate permanently in the code somewhere?

```
entity_id: light.philips_lct010_7bfa4702_level_light_color_on_off
brightness_pct: 20
transition: 1
```

**Comment by Adminiuga** [comment]
configure a light profile???

**Comment by RefineryX** [comment]
> configure a light profile???

Would this work as a system wide setting for transitioning the brightness and colour changes? I.e, if I decided to change the brightness from Lovelace or HomeKit, the transition would be 1s or whatever I decide?

If so... do you have any guidance on how I would go about enabling that?

**Comment by Adminiuga** [comment]
https://www.home-assistant.io/integrations/light/

**Comment by Adminiuga** [comment]
but i haven't tried it

**Comment by RefineryX** [comment]
Yes, I was able to search google and find the exact same link above. The question I was asking was how do I apply it to this use case? After reading the documentation, I am not sure I am understanding it correctly. It appears that the [light integration](https://www.home-assistant.io/integrations/light/) allows users to to track and control either when the light is switched on or switched off.

But I do not see anything for changing a light that is already on?

**On/Off transition works fine:** Currently, that already works fine and see that the light turns on/off with a smooth transition. No changes are required here.

**Transition when the bulb is already on:** The issue I am facing is when **changing the colour or brightness of a bulb that is already on**. I would like to keep all the settings exactly the same but just add a transition time of ``1s`` each time either the colour(+temp) or brightness is changed to give it a smooth transition. I think currently the default is set to ``0``.

**Comment by TheJulianJES** [comment]
Comment in other thread for visibility here: https://github.com/zigpy/zha-device-handlers/issues/297#issuecomment-739910539

**Comment by RefineryX** [comment]
Thanks. I am going to assume that the light_profiles does not work as you mentioned in your previous comment.

Trying to piece this together in my mind and thanks for bearing with me haha.

I am looking at the file you linked too (https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/light.py#L195).

If I managed to find that file on my system, what would I update on there?
What would be the downsides of editing that file? Is there a risk that it would end up being overwritten with every release?

**Comment by TheJulianJES** [comment]
It would need to be `else 10` instead of `else 1` at the end of the line. 1 is 1/10th of a second as the default transition time. You could download the Hass source (for the version that you're running) and put the whole zha folder in your custom components directory. Then modify the light.py file. If you update, you need to do this before updating if possible, as things will break sooner or later otherwise. Tbh I wouldn't recommend to do this.

**Comment by Adminiuga** [comment]
per https://community.home-assistant.io/t/light-profiles-csv/91407/5 seems like you need to create the `light_profiles.csv` file in your config directory and have a line with `group.all_lights.default` entity ID with
```
group.all_lights.default,x_color_float_number,y_color_float_number,brightness_number,default_transition_number
```

**Comment by RefineryX** [comment]
> put the whole zha folder in your custom components directory. Then modify the light.py file

@TheJulianJES thanks for the information and I agree with you, that seems pretty 'hacky' and a long route just to be able to change the transition of the lights. I have a range of Zigbee devices and concerned about keeping my own version in the customs_compotent folder.



> per https://community.home-assistant.io/t/light-profiles-csv/91407/5 seems like you need to create the `light_profiles.csv` file in your config directory and have a line with `group.all_lights.default` entity ID with

I am out of my depth with that as I really don't understand i. @TheJulianJES, you mentioned that this would not work, right?

**Comment by RefineryX** [comment]
So I have created a ``light_profiles.csv`` file and added the below. I am going to test using my living room lamp first but I don't see any difference.
```
id,x,y,brightness,transition
light.living_room_lamp,0.5119,0.4147,144,1
```

Its a real shame that I have to specify x,y and brightness settings. Does this mean every time the lamp is turned on, it will default to those settings?

**Comment by Adminiuga** [comment]
1. There should not be any headers
2. I did not test with individual lights
3. yes

**Comment by RefineryX** [comment]
Hmmm, still doesn't work. I event put the transition to 15 seconds to test.

No worries anyways, appreciate both your both - thank you @Adminiuga and @TheJulianJES. 

I am going to switch everything over to Deconz this weekend.

**Comment by Adminiuga** [comment]
I've tested with `group.all_lights.default` and can confirm it is working.

>light.living_room_lamp,0.5119,0.4147,144,15

This is supposed to be `light.living_room_lamp.default` 
![image](https://user-images.githubusercontent.com/5826160/101507486-95e05b00-3944-11eb-9133-4e8fd044a7df.png)

The only downside, it would always do a color transition too. To fix that a PR is required.

**Comment by Adminiuga** [comment]
I've tested it with both `group.all_lights.default` and `entity_id.default` and can confirm it is working as expected, but in the end it does depend on the device, whether it supports the color transition or not.

Test setup:
1. `light_profiles.csv` with the following content
```
light.ikea_of_sweden_tradfri_bulb_e26_ws_clear_806lm_f14a95fe_level_light_color_on_off.default,0.0,0.100,100,5
group.all_lights.default,0.343,0.159,250,5
light.ledvance_br30_rgbw_32c50000_level_light_color_on_off.default,0.,0.1,250,5
```
3. Ledvance Color bulb BR30 and GE45857 dimmer
4. Ledvance was turned on with red color using a service call, then turned off
5. Ledvance was turned on from UI here's content of the service call
![image](https://user-images.githubusercontent.com/5826160/101512638-3df82300-3949-11eb-85b7-3b2905ff4edf.png)

and it corresponds to light profile settings for that specific entity. It smoothly increased brightenss and transitioned from red to blue as expected

6. GE45857 was set to on with brightness 7, then turned off using service call
7. GE45857 was turned on using UI and the service was called with
![image](https://user-images.githubusercontent.com/5826160/101513085-c24aa600-3949-11eb-9018-ce0e70a4514a.png)

that corresponds to light profile default setting for all lights
and light correctly transitioned into specified state, but couldn't set the color, because it is just a simple dimmer
![image](https://user-images.githubusercontent.com/5826160/101513418-240b1000-394a-11eb-9bc3-be5c4c25216d.png)

**Comment by RefineryX** [comment]
Thanks. Yes, needed the ``.default``. But again, can I clarify... this is just for turning on and off the lights right? And, does not address my issue?

**Comment by Adminiuga** [comment]
No, it does not.

**Comment by RefineryX** [comment]
Hmm... okay, let's ignore that.

Let's leave this open incase anyone can think of a way to get this to work. Does anyone know how Deconz handle the transitions and how it works?  When requesting a change of brightness or colour when the lights are connected with Deconz, it works.
