### ISSUE TITLE
Moes 3 Gang & Switch Embedded Light Touch Switch/ Scene Switch TS0726 by _TZ3002_vaq2bfcu

### ISSUE THREAD

**Issue by vpaulos** [zigpy/zha-device-handlers#3154]
### Problem description

link for device - https://moeshouse.com/products/eu-star-ring-smart-light-switch?variant=40218622165073
version - TS0726 by _TZ3002_vaq2bfcu
problem - when you push for 1 button on the ZHA, all 3 channels will switch on or off. The same situation, if you try to push on every of 6 buttons of this device. PLease Help

![image](https://github.com/zigpy/zha-device-handlers/assets/48480823/04fd61f5-4163-4776-80e7-84b33c0827f5)

simple press button on device is working normal. for example i was push second channel button. In ZHA all show correct.
![image](https://github.com/zigpy/zha-device-handlers/assets/48480823/53f3c0db-82f6-47b1-b533-93464ba35336)

but if I press one of the button on ZHA directly - all channel will switch on|off.

![image](https://github.com/zigpy/zha-device-handlers/assets/48480823/54d6e19f-e334-430d-bec8-32d02a476b25)

 

### Solution description

there is no solution

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by VBenkovskyy** [comment]
Hello, I solved this issue [here](https://github.com/Koenkk/zigbee2mqtt/issues/27167#issuecomment-2888708485)

**Comment by SgtFlippy** [comment]
> Hello, I solved this issue [here](https://github.com/Koenkk/zigbee2mqtt/issues/27167#issuecomment-2888708485)

That's for Z2M though, this question is for ZHA.
I have the same issue for my Bseed 2 and 3 gang switches (same hardware).
I wanted to use several as remotes for the others and wanted to reflect the statuslight, but it's not possible, when I change the status through HA, both lights turn on/off.

**Comment by bugyaru** [comment]
Hello, I solved this issue.
Previously, I had a problem with TS0013, which was solved by adding `ts001x.py` and `__init__.py` from the folder https://github.com/zigpy/zha-device-handlers/tree/master/zhaquirks/tuya to /config/custom_zha_quirks/tuya and also added [ts0601_switch.py](https://raw.githubusercontent.com/zigpy/zha-device-handlers/refs/heads/master/zhaquirks/tuya/ts0601_switch.py) ​​there.

**Comment by naghtan-droid** [comment]
I tried use that files and nothing, trying to add manually in ts0601_switch, remove and add again and the same...  I add here class TuyaDoubleSwitchTO(TuyaSwitch):
    """Tuya double channel switch time on out cluster device.""" It is the right place?

**Comment by mustiks** [comment]
@SgtFlippy @naghtan-droid 
After 12 hours of continuous debugging, I found the solution for 3 gang bseed switch TS0726 _TZ3002_iedhxgyi

[ts0762.py](https://github.com/user-attachments/files/25043549/ts0762.py)

**Comment by rodillo69** [comment]
Solution: Write operation_mode attribute (0x5000) to switch from scene mode to command mode                                                            
                                                                                                                                                         
  I had the same issue with Beseed/Moes TS0726 switches (2-gang _TZ3002_zjuvw9zf and 1-gang _TZ3002_jn2x20tg). Physical buttons worked independently, but
   toggling from ZHA activated all gangs simultaneously.    

  Root cause

  The TS0726 reports as SCENE_SELECTOR and ships with attribute 0x5000 (operation_mode) = 1 on the OnOff cluster (endpoint 1). This puts it in
  event/scene mode, where any On/Off command triggers all relays together.

  Setting 0x5000 = 0 switches it to command mode, enabling individual per-gang relay control.

  Key details discovered during debugging

  - Attribute 0x5000 uses enum8 type (not uint8_t) — writing the wrong type returns INVALID_DATA_TYPE
  - The attribute only exists on endpoint 1 (EP2 returns UNSUPPORTED_ATTRIBUTE, which is expected)
  - These devices have an endpoint 242 (Green Power, profile 0xA1E0) that must be included in the quirk signature, otherwise zigpy rejects the match with
   "endpoint list mismatch"
  - After writing operation_mode=0, the device confirms by reporting back operation_mode=0 via attribute report

  Custom quirk

  Save as ts0726_switch.py in your custom_zha_quirks folder, then remove and re-pair the device:

  """Tuya TS0726 1/2-gang switch (Beseed/Moes).

  Fixes the issue where toggling one gang activates all gangs by:
  1. Replacing OnOff with a custom cluster that includes Tuya attribute 0x5000
  2. Writing 0x5000=0 (command mode) on initialization to enable per-gang control

  Based on the ts001x.py quirk pattern from zha-device-handlers.
  """

  from typing import Final

  from zigpy.profiles import zha
  import zigpy.types as t
  from zigpy.zcl.clusters.general import (
      Basic,
      Groups,
      Identify,
      OnOff,
      Ota,
      Scenes,
      Time,
  )
  from zigpy.zcl.foundation import ZCLAttributeDef

  # Green Power endpoint constants
  GP_PROFILE_ID = 0xA1E0
  GP_DEVICE_TYPE = 0x0061
  GP_CLUSTER_ID = 0x0021

  from zhaquirks.const import (
      DEVICE_TYPE,
      ENDPOINTS,
      INPUT_CLUSTERS,
      MODELS_INFO,
      OUTPUT_CLUSTERS,
      PROFILE_ID,
  )
  from zhaquirks.tuya import (
      EnchantedDevice,
      TuyaSwitch,
      TuyaZBE000Cluster,
      TuyaZBExternalSwitchTypeCluster,
      TuyaZBOnOffAttributeCluster,
  )


  class TuyaTS0726OnOffCluster(TuyaZBOnOffAttributeCluster):
      """OnOff cluster for TS0726 with operation_mode attribute (0x5000).

      Attribute 0x5000 controls the switch operation mode:
        0 = command mode (individual relay control)
        1 = event/scene mode (all relays toggle together)
      """

      class AttributeDefs(TuyaZBOnOffAttributeCluster.AttributeDefs):
          operation_mode: Final = ZCLAttributeDef(
              id=0x5000, type=t.enum8
          )

      async def apply_custom_configuration(self, *args, **kwargs):
          """Set operation_mode to 0 (command mode) for individual gang control."""
          self.debug("Writing operation_mode=0 (command mode) on EP %s",
                     self.endpoint.endpoint_id)
          try:
              await self.write_attributes({"operation_mode": 0})
          except Exception as e:
              self.warning("Failed to write operation_mode: %s", e)
          await super().apply_custom_configuration(*args, **kwargs)


  class TuyaTS0726_2Gang(EnchantedDevice, TuyaSwitch):
      """Tuya TS0726 2-gang switch (Beseed/Moes) with 0xE000/0xE001 clusters."""

      signature = {
          MODELS_INFO: [("_TZ3002_zjuvw9zf", "TS0726")],
          ENDPOINTS: {
              1: {
                  PROFILE_ID: zha.PROFILE_ID,
                  DEVICE_TYPE: zha.DeviceType.SCENE_SELECTOR,
                  INPUT_CLUSTERS: [
                      Basic.cluster_id,          # 0x0000
                      Identify.cluster_id,       # 0x0003
                      Groups.cluster_id,         # 0x0004
                      Scenes.cluster_id,         # 0x0005
                      0x0006,                    # OnOff
                      0xE000,                    # Tuya Manufacturer Specific
                      0xE001,                    # Tuya External Switch Type
                  ],
                  OUTPUT_CLUSTERS: [
                      Time.cluster_id,           # 0x000A
                      Ota.cluster_id,            # 0x0019
                  ],
              },
              2: {
                  PROFILE_ID: zha.PROFILE_ID,
                  DEVICE_TYPE: zha.DeviceType.SCENE_SELECTOR,
                  INPUT_CLUSTERS: [
                      Groups.cluster_id,         # 0x0004
                      Scenes.cluster_id,         # 0x0005
                      0x0006,                    # OnOff
                      0xE001,                    # Tuya External Switch Type
                  ],
                  OUTPUT_CLUSTERS: [],
              },
              242: {
                  PROFILE_ID: GP_PROFILE_ID,
                  DEVICE_TYPE: GP_DEVICE_TYPE,
                  INPUT_CLUSTERS: [],
                  OUTPUT_CLUSTERS: [GP_CLUSTER_ID],
              },
          },
      }

      replacement = {
          ENDPOINTS: {
              1: {
                  PROFILE_ID: zha.PROFILE_ID,
                  DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                  INPUT_CLUSTERS: [
                      Basic.cluster_id,
                      Identify.cluster_id,
                      Groups.cluster_id,
                      Scenes.cluster_id,
                      TuyaTS0726OnOffCluster,
                      TuyaZBE000Cluster,
                      TuyaZBExternalSwitchTypeCluster,
                  ],
                  OUTPUT_CLUSTERS: [Ota.cluster_id],
              },
              2: {
                  PROFILE_ID: zha.PROFILE_ID,
                  DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                  INPUT_CLUSTERS: [
                      Groups.cluster_id,
                      Scenes.cluster_id,
                      TuyaTS0726OnOffCluster,
                      TuyaZBExternalSwitchTypeCluster,
                  ],
                  OUTPUT_CLUSTERS: [],
              },
              242: {
                  PROFILE_ID: GP_PROFILE_ID,
                  DEVICE_TYPE: GP_DEVICE_TYPE,
                  INPUT_CLUSTERS: [],
                  OUTPUT_CLUSTERS: [GP_CLUSTER_ID],
              },
          },
      }


  class TuyaTS0726_1Gang(EnchantedDevice, TuyaSwitch):
      """Tuya TS0726 1-gang switch (Beseed/Moes) with 0xE000/0xE001 clusters."""

      signature = {
          MODELS_INFO: [("_TZ3002_jn2x20tg", "TS0726")],
          ENDPOINTS: {
              1: {
                  PROFILE_ID: zha.PROFILE_ID,
                  DEVICE_TYPE: zha.DeviceType.SCENE_SELECTOR,
                  INPUT_CLUSTERS: [
                      Basic.cluster_id,          # 0x0000
                      Identify.cluster_id,       # 0x0003
                      Groups.cluster_id,         # 0x0004
                      Scenes.cluster_id,         # 0x0005
                      0x0006,                    # OnOff
                      0xE000,                    # Tuya Manufacturer Specific
                      0xE001,                    # Tuya External Switch Type
                  ],
                  OUTPUT_CLUSTERS: [
                      Time.cluster_id,           # 0x000A
                      Ota.cluster_id,            # 0x0019
                  ],
              },
              242: {
                  PROFILE_ID: GP_PROFILE_ID,
                  DEVICE_TYPE: GP_DEVICE_TYPE,
                  INPUT_CLUSTERS: [],
                  OUTPUT_CLUSTERS: [GP_CLUSTER_ID],
              },
          },
      }

      replacement = {
          ENDPOINTS: {
              1: {
                  PROFILE_ID: zha.PROFILE_ID,
                  DEVICE_TYPE: zha.DeviceType.ON_OFF_LIGHT,
                  INPUT_CLUSTERS: [
                      Basic.cluster_id,
                      Identify.cluster_id,
                      Groups.cluster_id,
                      Scenes.cluster_id,
                      TuyaTS0726OnOffCluster,
                      TuyaZBE000Cluster,
                      TuyaZBExternalSwitchTypeCluster,
                  ],
                  OUTPUT_CLUSTERS: [Ota.cluster_id],
              },
              242: {
                  PROFILE_ID: GP_PROFILE_ID,
                  DEVICE_TYPE: GP_DEVICE_TYPE,
                  INPUT_CLUSTERS: [],
                  OUTPUT_CLUSTERS: [GP_CLUSTER_ID],
              },
          },
      }

  Adapting for 3-gang or other manufacturer IDs

  For _TZ3002_vaq2bfcu (3-gang) or other variants, you'd need to:
  1. Add the manufacturer ID to MODELS_INFO
  2. Add endpoint 3 (and beyond) to both signature and replacement with the same cluster pattern as EP2

  The core fix (writing 0x5000=0 with enum8 type) should work for all TS0726 variants since they share the same firmware behavior.

  Tested and confirmed working on Home Assistant 2026.1.3 with ZHA + Inswift ZBM-MG24 coordinator.
